### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Fietsbantje**
This fixes the git conflict and the upstream branches while updating the requirement.txt file and adding the environment.yml file.

### CODE REVIEW

**Comment by Fietsbantje** [comment]
merge pull requests

**Comment by Fietsbantje** [comment]
merge pull requests

**Review by Fietsbantje — COMMENTED** [review]
I agree with the changes

**Comment by Fietsbantje** [comment]
I agree with the changes

**Comment by fausto-coppi** [comment]
Looks clean, ready to push!

**Comment by fausto-coppi** [comment]
Closed pull request by accident and reopened it.

**Review by fausto-coppi — APPROVED** [review]
Looks good. Ready to merge.

**Comment by Fietsbantje** [comment]
Grazie Coppi! I will merge these commits into master.

**Pull request merged**
